name: Purim 1946
favicon: null
layout_spectrum: 0.365041368175298
typography_spectrum: 0.4199091559275985
title: Purim 1946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.055380623787641525
  lightness: 0.968851818004623
  saturation: 0.6571340970695019
  rhythmicContrast: 0.8193374476395547
purpose: []
