name: Purim 1946
favicon: null
layout_spectrum: 0.365041368175298
typography_spectrum: 0.4199091559275985
title: Purim 1946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121212'
    - '#474747'
    - '#7c7c7c'
    - '#9b9b9b'
    - '#d2d2d2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
